depost/config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'sessions/create'
  get 'sessions/destroy'


  resources :support_requests, only: %i[ index update ]
  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
end

depost/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

depost/app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
            current_item.quantity += 1
        else
            current_item = line_items.build(product_id: product.id)
        end
        current_item
    end

    def total_price
        line_items.sum { |item| item.total_price }
    end
end

depost/app/models/line_item.rb
class LineItem < ApplicationRecord
  def total_price
    product.price * quantity
  end

  belongs_to :order, optional: true
  belongs_to :product
  belongs_to :cart, optional: true

end

depost/app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    enum pay_type: {
        "Check" => 0,
        "Credit card" => 1,
        "Purchase order" => 2
    }

    validates :name, :address, :email, presence: true
    validates :pay_type, inclusion: pay_types.keys

    def add_line_items_from_cart(cart)
        cart.line_items.each do |item|
            item.cart_id = nil
            line_items << item
        end
    end

end

depost/app/models/product.rb
class Product < ApplicationRecord
    validates :title, :description, :image_url, presence: true
    validates :title, uniqueness: true
    validates :price, numericality: { greater_than_or_equal_to: 0.01 }
    validates :image_url, allow_blank: true, format: {
        with:   %r{\.(gif|jpeg|png|jpg)\z}i,
        message: 'must be a URL for GIF, JPG or PNG image'
    }

    has_many :line_items

    before_destroy :ensure_not_referenced_by_any_line_item

    private
        def ensure_not_referenced_by_any_line_item
            unless line_items.empty?
                errors.add(:base, 'Line Items present')
                throw :abort
            end
        end
end

depost/app/models/support_request.rb
class SupportRequest < ApplicationRecord
    belongs_to :order, optional: true
end

depost/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  after_destroy :ensure_an_admin_remains

  class Error < StandardError
  end

  private

  def ensure_an_admin_remains
    if User.count.zero?
      raise Error.new "Can't delete last user"
    end
  end
end

depost/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

depost/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

depost/app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_action :authorize
  include CurrentCart
  before_action :set_cart
  def index

    if params[:set_locale]
      redirect_to store_index_url(locale: params[:set_locale])
    else
      @products = Product.order(:title)
    end

  end

  # def set_cart
  #   @cart = Cart.find(session[:cart_id])
  # rescue ActiveRecord::RecordNotFound
  #   @cart = Cart.add
  #   session[:cart_id] = @cart.id
  #   session[:counter] = 0
  # end
end

depost/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created." }
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  rescue_from 'User::Error' do |exception|
    redirect_to users_url, notice: exception.message
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

depost/app/helpers/admin_helper.rb
module AdminHelper
end

depost/app/helpers/application_helper.rb
module ApplicationHelper
end

depost/app/helpers/carts_helper.rb
module CartsHelper
end

depost/app/helpers/line_items_helper.rb
module LineItemsHelper
end

depost/app/helpers/orders_helper.rb
module OrdersHelper
end

depost/app/helpers/products_helper.rb
module ProductsHelper
end

depost/app/helpers/sessions_helper.rb
module SessionsHelper
end

depost/app/helpers/store_helper.rb
module StoreHelper
end

depost/app/helpers/users_helper.rb
module UsersHelper
end

depost/app/views/admin/index.html.erb
<div class="w-full">
  <h1 class="mx-auto text-lg font-bold text-4xl">Welcome</h1>
  <p>It's <%= Time.now %>.
    We have <%= pluralize(@total_orders, "order") %>.
  </p>
</div>

depost/app/views/layouts/_cart.html.erb
<% if cart and not cart.line_items.empty? %>
  <div id="cart" class="bg-white rounded p-2">
    <%= render cart %>
  </div>
<% else %>
  <div id="cart"></div>
<% end %>

depost/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="bg-gray-200 p-6">
    <%#=
      <aside data-controller="locale">
        <%= form_tag store_index_path, class: 'locale' do %>
          <%# <%= select_tag 'set_locale',
            options_for_select(LANGUAGES, I18n.locale.to_s),
            onchange: 'this.form.submit()' %>
          <%# <%= submit_tag 'submit', data: {'locale-target' => 'submit'} %>
        <%# <% end %>
      <%# </aside> %>

      <%= image_tag 'giving-block.svg', alt: 'Bookshelf'%>
      <h1><%= @page_title %></h1>
    </header>

    <section class="flex min-h-screen">
      <nav class="bg-gray-800 p-8">
        <%= render partial: "layouts/cart", locals: {cart: @cart } %>
        <ul class="text-gray-300 leading-8">
          <li><a href="/"><%= t('.home') %></a></li>
          <li><a href="/products"><%= t('.products') %></a></li>
          <li><a href="/news"><%= t('.news') %></a></li>
          <li><a href="/contact"><%= t('.contact') %></a></li>
        </ul>

        <% if session[:user_id] %>
          <hr class="my-2">

          <ul class="text-gray-300 leading-8">
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= button_to 'Logout', logout_path, method: :delete %></li>
          </ul>
        <% end %>

      </nav>

      <main class="container mx-auto mt-4 px-5 flex">
        <%= yield %>
      </main>
    </section>

  </body>
</html>